### ISSUE TITLE
Provide Homer content for JHU to review

### ISSUE THREAD

**Issue by cyork** [jhu-digital-manuscripts/AnIOp#19]
JHU will review textual resources from Eldarion.

**Comment by cyork** [comment]
images, metadata are needed.

**Comment by jtauber** [comment]
For the Homer Multitext project, the raw images are here:

http://www.homermultitext.org/hmt-image-archive/venetus-a/

and there is an Image Citation Tool at:

http://www.homermultitext.org/ict2/

which uses OpenSeadragon but I'm not 100% sure how the service it is called works (although I know it is custom).

The overall data is here:

https://github.com/homermultitext/hmt-archive

which includes the transcriptions in CEX format (which we'll probably looking at importing into ATLAS and serving up via GraphQL).

**Comment by markpatton** [comment]
The raw images directories has images of a book. What book is it? What is the CITE URN for that book? The images use a particular naming scheme I assume is associated with CITE. What scheme is it and how does one go from a cite URN to an image file? 

The overall data link seems to have metadata in a custom format which describes resources in the archive/ directory. What does this whole structure represent? Many different homer texts? Within that structure what do we want to be able to see in the JHU infrastructure? Just the particular book from that raw images directory? If so, what metadata, transcripts, etc do we want associated with that book?

It seems like one is supposed to walk the metadata starting from https://github.com/homermultitext/hmt-archive/blob/master/release-candidates/hmt-2019_1_rc2.cex in order to understand the resources in the archive/ directory.  Any hints?

**Comment by markpatton** [comment]
The content is complicated, but can be imported into our system. The issue is selecting what to import.
