### ISSUE TITLE
Propose approach for associating iiif and cite resources

### ISSUE THREAD

**Issue by markpatton** [jhu-digital-manuscripts/AnIOp#29]

**Comment by jacobwegner** [comment]
I'll mention this on the call, but just wanted to add that as Eldarion continues work on the HMT ATLAS server, we're intending to have an example of an alignment endpoint that given a CITE URN would allow retrieval of a translation alignment for a given folio.

I'll provide an update once we have something, but at a high level, given a CITE URN for a folio, we'd return a data structure with a translation alignment and bounding box info so that the client could display the alignment data in a meaningful way.

**Comment by markpatton** [comment]
@jacobwegner 

That makes sense. One issue to figure out is how to reference the image that the bounding box is for? That image has a CITE urn in the cex files so I guess it could be used again? Or perhaps a reference to the IIIF image URI?

**Comment by jacobwegner** [comment]
@markpatton I'll try and have a better answer for this by our next call, as I think we'll have made more progress with the data ingestion to better reason around this.

Off the cuff, we could probably do both (the image's CITE urn _AND_ the IIIF image URI).

**Comment by htpvu** [comment]
Decision: have an approach to use: ad-hoc agreement (shared understanding) instead of a service handshake.  close this ticket
