### ISSUE TITLE
Knowledge transferring from Reuben to John

### ISSUE THREAD

**Issue by htpvu** [jhu-digital-manuscripts/AnIOp#44]
Please enumerate the points to be covered in this knowledge transfer.

**Comment by jabrah** [comment]
So far, I have been looking looking over the code for the current demo on @GroovinChip's fork. I can enumerate specific questions later

**Comment by GroovinChip** [comment]
@jabrah and I plan to meet this afternoon to discuss this

**Comment by cyork** [comment]
@GroovinChip Please record the ongoing discussion points in this document 
https://docs.google.com/document/d/1AmQdS1M6_-I63tC9BlKAByXJg0m9hm7yapeo5simw-Q/edit

**Comment by jabrah** [comment]
I've added sort of a brain dump of some info about Mirador plugins and the current WA plugin

**Comment by jabrah** [comment]
The information I filled out in the document linked above summarizes the the topics Reuben and I discussed. I believe the topics we discussed is sufficient to catch me up on the project. I got a better understanding of the workings of the project and at least enabled me to follow conversations about the project.

I should have enough information now to be able to understand the context of issues in the viewer in order to keep up-to-date with the project. I would be fine closing this ticket.
